In [2]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\vitor\appdata\local\programs\python\python312\lib\site-packages (2.2.0)
Requirement already satisfied: openpyxl in c:\users\vitor\appdata\local\programs\python\python312\lib\site-packages (3.1.2)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\vitor\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vitor\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vitor\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vitor\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: et-xmlfile in c:\users\vitor\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\vitor\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd
import os 
import openpyxl as op

In [4]:
vendas_df = pd.read_excel("data/Vendas.xlsx")

In [5]:
vendas_df

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
100995,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
100996,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
100998,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266